2018-03-16 09:31:05,678 ERROR 6800 [-/::1/-/16ms GET /api/posts] nodejs.TypeError: Cannot set property 'body' of undefined
    at Object.exports.index (E:\learn\egg\learn\app\controller\posts.js:2:19)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.objectControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:112:26)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 6800
hostname: YANFA-020

2018-03-16 17:12:26,353 ERROR 7980 [-/::1/-/20ms GET /userget] nodejs.TypeError: ctx.service.user.find is not a function
    at TopicController.userget (E:\learn\egg\learn\app\controller\posts.js:24:45)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 7980
hostname: YANFA-020

2018-03-16 17:13:41,419 ERROR 7492 [-/::1/-/11ms GET /userget] nodejs.TypeError: ctx.service.user.find is not a function
    at TopicController.userget (E:\learn\egg\learn\app\controller\posts.js:24:45)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 7492
hostname: YANFA-020

2018-03-16 17:13:45,500 ERROR 7492 [-/::1/-/1ms GET /userget] nodejs.TypeError: ctx.service.user.find is not a function
    at TopicController.userget (E:\learn\egg\learn\app\controller\posts.js:24:45)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 7492
hostname: YANFA-020

2018-03-16 17:15:04,895 ERROR 7488 [-/::1/-/6ms GET /userget] nodejs.ReferenceError: ctx is not defined
    at TopicController.userget (E:\learn\egg\learn\app\controller\posts.js:24:45)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 7488
hostname: YANFA-020

2018-03-16 17:15:05,788 ERROR 7488 [-/::1/-/0ms GET /userget] nodejs.ReferenceError: ctx is not defined
    at TopicController.userget (E:\learn\egg\learn\app\controller\posts.js:24:45)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 7488
hostname: YANFA-020

2018-03-16 17:18:24,147 ERROR 9092 [-/::1/-/8ms GET /userget] nodejs.ReferenceError: ctx is not defined
    at TopicController.userget (E:\learn\egg\learn\app\controller\posts.js:24:45)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 9092
hostname: YANFA-020

2018-03-16 17:18:26,723 ERROR 9092 [-/::1/-/1ms GET /userget] nodejs.ReferenceError: ctx is not defined
    at TopicController.userget (E:\learn\egg\learn\app\controller\posts.js:24:45)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 9092
hostname: YANFA-020

2018-03-21 16:58:51,119 ERROR 9292 [-/127.0.0.1/-/11ms POST /upload] nodejs.TypeError: Cannot read property 'put' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:13:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 9292
hostname: YANFA-020

2018-03-21 16:59:51,306 ERROR 10904 [-/127.0.0.1/-/17ms POST /upload] nodejs.TypeError: Cannot read property 'put' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:13:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 10904
hostname: YANFA-020

2018-03-21 17:01:00,344 ERROR 10660 [-/127.0.0.1/-/35ms POST /upload] nodejs.TypeError: Cannot read property 'put' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 10660
hostname: YANFA-020

2018-03-21 17:02:09,623 ERROR 9428 [-/127.0.0.1/-/12ms POST /upload] nodejs.TypeError: Cannot read property 'put' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 9428
hostname: YANFA-020

2018-03-21 17:04:20,076 ERROR 10508 [-/127.0.0.1/-/13ms POST /upload] nodejs.TypeError: Cannot read property 'put' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 10508
hostname: YANFA-020

2018-03-21 17:10:00,158 ERROR 5232 [-/127.0.0.1/-/18ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 5232
hostname: YANFA-020

2018-03-21 17:16:31,007 ERROR 6420 [-/127.0.0.1/-/17ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6420
hostname: YANFA-020

2018-03-21 17:16:53,879 ERROR 11176 [-/127.0.0.1/-/19ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 11176
hostname: YANFA-020

2018-03-21 17:25:08,643 ERROR 7888 [-/127.0.0.1/-/11ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:31:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 7888
hostname: YANFA-020

2018-03-21 17:32:38,931 ERROR 1808 [-/127.0.0.1/-/11ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:13:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 1808
hostname: YANFA-020

2018-03-21 17:34:46,320 ERROR 9208 [-/127.0.0.1/-/12ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 9208
hostname: YANFA-020

2018-03-21 17:37:38,174 ERROR 7428 [-/127.0.0.1/-/13ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 7428
hostname: YANFA-020

2018-03-21 17:39:02,647 ERROR 10044 [-/127.0.0.1/-/11ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 10044
hostname: YANFA-020

2018-03-21 17:43:17,085 ERROR 11004 [-/127.0.0.1/-/8ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 11004
hostname: YANFA-020

2018-03-21 17:52:53,888 ERROR 6788 [-/127.0.0.1/-/13ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6788
hostname: YANFA-020

2018-03-21 17:54:39,908 ERROR 9208 [-/127.0.0.1/-/8ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 9208
hostname: YANFA-020

2018-03-21 17:55:32,097 ERROR 8004 [-/127.0.0.1/-/12ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 8004
hostname: YANFA-020

2018-03-21 17:56:08,649 ERROR 8004 [-/127.0.0.1/-/6ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 8004
hostname: YANFA-020

2018-03-21 17:56:24,267 ERROR 10644 [-/127.0.0.1/-/8ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 10644
hostname: YANFA-020

2018-03-21 17:56:59,085 ERROR 7892 [-/127.0.0.1/-/10ms POST /upload] nodejs.TypeError: ctx.oss.put is not a function
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:14:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 7892
hostname: YANFA-020

2018-03-21 18:01:58,764 ERROR 6420 [-/127.0.0.1/-/11ms POST /upload] nodejs.ReferenceError: dataBuffer is not defined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6420
hostname: YANFA-020

2018-03-21 18:02:31,902 ERROR 7660 [-/127.0.0.1/-/27ms POST /upload] nodejs.Error: ..\src\Image.cc:470 Image uninitialized.
    at WrappedImage.encode (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:88:37)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 7660
hostname: YANFA-020

2018-03-22 09:21:57,683 ERROR 6228 [-/127.0.0.1/-/12ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6228
hostname: YANFA-020

2018-03-22 09:23:18,188 ERROR 6284 [-/127.0.0.1/-/13ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6284
hostname: YANFA-020

2018-03-22 09:25:37,757 ERROR 6768 [-/127.0.0.1/-/10ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6768
hostname: YANFA-020

2018-03-22 09:26:08,578 ERROR 3244 [-/127.0.0.1/-/8ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 3244
hostname: YANFA-020

2018-03-22 09:26:54,153 ERROR 1884 [-/127.0.0.1/-/12ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 1884
hostname: YANFA-020

2018-03-22 09:27:34,121 ERROR 6632 [-/127.0.0.1/-/9ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6632
hostname: YANFA-020

2018-03-22 09:28:40,208 ERROR 3164 [-/127.0.0.1/-/22ms POST /upload] nodejs.Error: ..\src\Image.cc:470 Image uninitialized.
    at WrappedImage.encode (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:88:37)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:66)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 3164
hostname: YANFA-020

2018-03-22 09:48:58,908 ERROR 5268 [-/127.0.0.1/-/9ms POST /upload] nodejs.Error: ..\src\Image.cc:470 Image uninitialized.
    at WrappedImage.encode (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:88:37)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:66)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 5268
hostname: YANFA-020

2018-03-22 09:49:28,089 ERROR 3192 [-/127.0.0.1/-/11ms POST /upload] nodejs.Error: ..\src\Image.cc:470 Image uninitialized.
    at WrappedImage.encode (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:88:37)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:66)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 3192
hostname: YANFA-020

2018-03-22 09:49:59,725 ERROR 7488 [-/127.0.0.1/-/40ms POST /upload] nodejs.Error: ..\src\Image.cc:470 Image uninitialized.
    at WrappedImage.encode (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:88:37)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:66)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 7488
hostname: YANFA-020

2018-03-22 09:50:22,493 ERROR 7100 [-/127.0.0.1/-/31ms POST /upload] nodejs.ENOENTError: ENOENT: no such file or directory, open 'E:\learn\egg\learn\egg-multipart-test\flow1.png'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:88:12)
    at WrappedImage.save (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:15:76)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
errno: -4058
code: 'ENOENT'
syscall: 'open'
path: 'E:\\learn\\egg\\learn\\egg-multipart-test\\flow1.png'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ENOENTError'
pid: 7100
hostname: YANFA-020

2018-03-22 09:51:58,222 ERROR 6660 [-/127.0.0.1/-/13ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6660
hostname: YANFA-020

2018-03-22 09:52:51,312 ERROR 4616 [-/127.0.0.1/-/16ms POST /upload] nodejs.TypeError: Cannot read property 'url' of undefined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:24:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 4616
hostname: YANFA-020

2018-03-22 09:57:39,945 ERROR 6092 [-/127.0.0.1/-/72ms POST /upload] nodejs.Error: ..\src\Image.cc:341 Unknow format
    at WrappedImage.loadFromBuffer (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:54:22)
    at WrappedImage.loadFromBuffer (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:142:34)
    at Function.images.loadFromBuffer (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:214:27)
    at images (E:\learn\egg\learn\node_modules\_images@3.0.1@images\index.js:172:24)
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:16:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 6092
hostname: YANFA-020

2018-03-22 10:32:59,597 ERROR 4976 [-/127.0.0.1/-/8ms POST /upload] nodejs.ReferenceError: buffer2 is not defined
    at UploaderController.upload (E:\learn\egg\learn\app\controller\upload.js:13:76)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 4976
hostname: YANFA-020

2018-03-22 14:41:44,855 ERROR 6412 [-/127.0.0.1/-/55ms POST /api/banner] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'test.s_banner' doesn't exist
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES('首页', '', '')
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'test.s_banner\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES(\'首页\', \'\', \'\')'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_NO_SUCH_TABLEError'
pid: 6412
hostname: YANFA-020

2018-03-22 14:42:24,987 ERROR 6412 [-/127.0.0.1/-/4ms POST /api/banner] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'test.s_banner' doesn't exist
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES('第一', '', '')
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'test.s_banner\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES(\'第一\', \'\', \'\')'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_NO_SUCH_TABLEError'
pid: 6412
hostname: YANFA-020

2018-03-22 14:42:39,844 ERROR 6412 [-/127.0.0.1/-/3ms POST /api/banner] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'test.s_banner' doesn't exist
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES('第一', 'll', 'upload/1521700955785.png')
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'test.s_banner\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES(\'第一\', \'ll\', \'upload/1521700955785.png\')'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_NO_SUCH_TABLEError'
pid: 6412
hostname: YANFA-020

2018-03-22 14:43:48,370 ERROR 11236 [-/127.0.0.1/-/12ms POST /userget] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'shop.user' doesn't exist
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `id` = 1 LIMIT 0, 1
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'shop.user\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'SELECT * FROM `user` WHERE `id` = 1 LIMIT 0, 1'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_NO_SUCH_TABLEError'
pid: 11236
hostname: YANFA-020

2018-03-22 14:43:51,756 ERROR 11236 [-/127.0.0.1/-/5ms POST /userget] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'shop.user' doesn't exist
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `id` = 1 LIMIT 0, 1
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'shop.user\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'SELECT * FROM `user` WHERE `id` = 1 LIMIT 0, 1'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_NO_SUCH_TABLEError'
pid: 11236
hostname: YANFA-020

2018-03-22 14:44:19,147 ERROR 10568 [-/127.0.0.1/-/11ms POST /userget] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'shop.user' doesn't exist
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `id` = 1 LIMIT 0, 1
code: 'ER_NO_SUCH_TABLE'
errno: 1146
sqlMessage: 'Table \'shop.user\' doesn\'t exist'
sqlState: '42S02'
index: 0
sql: 'SELECT * FROM `user` WHERE `id` = 1 LIMIT 0, 1'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_NO_SUCH_TABLEError'
pid: 10568
hostname: YANFA-020

2018-03-22 14:45:40,579 ERROR 1664 [-/127.0.0.1/-/63ms POST /api/banner] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES('第一', '。。。', 'upload/1521701135593.png')
code: 'ER_NO_DEFAULT_FOR_FIELD'
errno: 1364
sqlMessage: 'Field \'id\' doesn\'t have a default value'
sqlState: 'HY000'
index: 0
sql: 'INSERT INTO `s_banner`(`name`, `tourl`, `url`) VALUES(\'第一\', \'。。。\', \'upload/1521701135593.png\')'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_NO_DEFAULT_FOR_FIELDError'
pid: 1664
hostname: YANFA-020

2018-03-23 11:30:19,834 ERROR 7784 [-/127.0.0.1/-/58ms PUT /api/banner/3] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2018-03-22T07:33:37.000Z' for column 'created_at' at row 1
    at Query.Sequence._packetToError (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    --------------------
    at Pool.query (E:\learn\egg\learn\node_modules\_mysql@2.15.0@mysql\lib\Pool.js:199:23)
    at E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:29:7
    at Promise (<anonymous>)
    at Pool.<anonymous> (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (E:\learn\egg\learn\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (E:\learn\egg\learn\node_modules\_ali-rds@3.0.1@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:65:19)
    at E:\learn\egg\learn\node_modules\_co@4.6.0@co\index.js:54:5
    sql: UPDATE `s_banner` SET `url` = 'upload/1521704014961.png', `tourl` = '2312', `name` = '11112asd', `created_at` = '2018-03-22T07:33:37.000Z' WHERE `id` = 3
code: 'ER_TRUNCATED_WRONG_VALUE'
errno: 1292
sqlMessage: 'Incorrect datetime value: \'2018-03-22T07:33:37.000Z\' for column \'created_at\' at row 1'
sqlState: '22007'
index: 0
sql: 'UPDATE `s_banner` SET `url` = \'upload/1521704014961.png\', `tourl` = \'2312\', `name` = \'11112asd\', `created_at` = \'2018-03-22T07:33:37.000Z\' WHERE `id` = 3'
headers: { 'Access-Control-Allow-Origin': '*' }
name: 'ER_TRUNCATED_WRONG_VALUEError'
pid: 7784
hostname: YANFA-020

2018-03-23 11:35:55,672 ERROR 7784 [-/127.0.0.1/-/9ms DELETE /api/banner/1] nodejs.ReferenceError: ctx is not defined
    at BannerController.destroy (E:\learn\egg\learn\app\controller\banner.js:34:23)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\loader\mixin\controller.js:84:20)
    at Object.callFn (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\index.js:44:21)
    at wrappedController (E:\learn\egg\learn\node_modules\_egg-core@4.4.1@egg-core\lib\utils\router.js:322:18)
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\learn\egg\learn\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\learn\egg\learn\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: { 'Access-Control-Allow-Origin': '*' }
pid: 7784
hostname: YANFA-020

2018-03-23 12:54:01,535 ERROR 7956 nodejs.ClusterClientNoResponseError: client no response in 1795283ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\learn\egg\learn\node_modules\_cluster-client@1.7.1@cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 7956
hostname: YANFA-020

